[package]
name = "teamwork-launcher"
version = "0.1.0"
edition = "2021"
default-run = "teamwork-launcher"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teamwork = { path = "../teamwork" }
iced = { git = "https://github.com/iced-rs/iced", features = ["tokio", "svg", "image"] }
iced_lazy = { git = "https://github.com/iced-rs/iced" }
async-stream = "0.3.3"
thiserror = "1"
static_assertions = "1.1.0"
iso_country = "0.1"
async-trait = "0.1.64"
serde = { version = "1", features = ["derive", "rc"] }
reqwest = "0.11.14"
serde_json = "1.0.93"
surge-ping = "0.7.3"
include_dir = "0.7.3"
lazy_static = "1.4.0"
itertools = "0.10.5"
nom = "7.1.3"
unidecode = "0.3.0"
sysinfo = "0.27.7"
platform-dirs = "0.3.0"

[dev-dependencies]
tokio = { version = "1.25.0", features = ["macros"] }
test-case = "3.0.0"

[build-dependencies]
anyhow = "1.0"
vergen = { version = "7", default-features = false, features = ["build", "rustc", "git"] }

