[package]
name = "teamwork-launcher"
description = "Launcher for Team Fortress 2 that uses Teamwork.tf as data source."
version = "0.2.0"
edition = "2021"
default-run = "teamwork-launcher"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teamwork = { path = "../teamwork" }
iced = { version = "0.7.0", features = ["tokio", "svg", "image", "system"] }
iced_lazy = { version = "0.4.0" }
async-stream = "0.3.3"
thiserror = "1"
static_assertions = "1.1.0"
iso_country = "0.1"
serde = { version = "1", features = ["derive", "rc"] }
reqwest = "0.11.14"
serde_json = "1.0.93"
surge-ping = "0.7.3"
include_dir = "0.7.3"
lazy_static = "1.4.0"
itertools = "0.10.5"
nom = "7.1.3"
unidecode = "0.3.0"
sysinfo = "0.27.7"
platform-dirs = "0.3.0"
bytesize = "1.1.0"

[dev-dependencies]
tokio = { version = "1.25.0", features = ["macros"] }
test-case = "3.0.0"

[build-dependencies]
anyhow = "1.0"
vergen = { version = "7", default-features = false, features = ["build", "rustc", "git"] }

[package.metadata.bundle]
identifier = "com.io.teamwork-launcher"
copyright = "Copyright (c) Iohann Rabeson 2023. All rights reserved."
osx_minimum_system_version = "10.8"

