[package]
name = "teamwork-launcher"
version = "0.1.0"
edition = "2021"
default-run = "teamwork-launcher"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teamwork = { path = "../teamwork" }
iced = { git = "https://github.com/iced-rs/iced", features = ["tokio", "svg", "image"] }
async-stream = "0.3.3"
futures = "0.3.26"
thiserror = "1"
static_assertions = "1.1.0"
iso_country = "0.1"
async-trait = "0.1.64"
serde = { version = "1", features = ["derive"] }
reqwest = "0.11.14"
serde_json = "1.0.93"
surge-ping = "0.7.3"
include_dir = "0.7.3"
lazy_static = "1.4.0"
itertools = "0.10.5"
nom = "7.1.3"
unidecode = "0.3.0"

[dev-dependencies]
tokio = { version = "1.25.0", features = ["macros"] }
