name: MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.8
      run: cargo build --verbose
    - name: Run tests
      env:
        TEST_TEAMWORK_API_KEY: {{ secrets.TEAMWORK_API_KEY }}
      run: cargo test --verbose
#    Currently disabled on OSX
#    When running on the Github Action runner, the application crashes with this error:
#    Error: the application graphics context could not be created
#    Iced does not support yet software renderers: https://github.com/iced-rs/iced/issues/1071
#    - name: Run integration test
#      run: cargo run -- --integration-test
