name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: teamwork-launcher-installer-${{ github.ref_name }}.exe
            asset_name: teamwork-launcher-windows.exe
          - os: macos-latest
            artifact_name: teamwork-launcher.zip
            asset_name: teamwork-launcher-macos.zip

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.8
        run: cargo build --release --locked

      - name: Bundle MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          cd teamwork-launcher
          cargo install cargo-bundle
          cargo bundle --release

      - name: Bundle Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd teamwork-launcher
          iscc.exe teamwork-launcher\innosetup\installer.iss /DMyAppVersion="${{  github.ref_name }}"

      - uses: thedoctor0/zip-release@0.7.1
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          type: 'zip'
          path: 'target/release/bundle/osx/'
          filename: 'target/release/teamwork-launcher.zip'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}