name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: teamwork-launcher-installer.exe
            asset_name: teamwork-launcher-installer-windows-${{ github.ref_name }}.exe
          - os: macos-latest
            artifact_name: teamwork-launcher.zip
            asset_name: teamwork-launcher-macos-${{ github.ref_name }}.zip

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Read Cargo.toml patch
        id: patch
        uses: juliangruber/read-file-action@v1
        with:
          path: ./ci/optim.txt

      - name: Patch Cargo.toml
        run: echo "${{ steps.patch.outputs.content }}" >> Cargo.toml

      - name: Build
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.8
          CI_PKG_VERSION: "${{  github.ref_name }}"
        run: cargo build --release --locked

      - name: Bundle MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          cd teamwork-launcher
          cargo install cargo-bundle
          cargo bundle --release

      - name: Bundle Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          iscc.exe ci\installer.iss /DMyAppVersion="${{  github.ref_name }}"

      - uses: thedoctor0/zip-release@0.7.1
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          type: 'zip'
          directory: 'target/release/bundle/osx/'
          filename: '../../teamwork-launcher.zip'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}